Brightscout/mattermost-plugin-jira

webapp/src/components/jira_field.jsx

https://github.com/mattermost/mattermost-plugin-jira/issues/867

[MI-2514]:Fixed issue #867 of jira

---

webapp/src/action_types/index.js
webapp/src/actions/index.ts
webapp/src/components/default_avatar/defaultAvatar.scss
webapp/src/components/default_avatar/default_avatar.tsx
webapp/src/components/jira_ticket_tooltip/index.ts
webapp/src/components/jira_ticket_tooltip/jira_ticket_tooltip.tsx
webapp/src/components/jira_ticket_tooltip/ticketStyle.scss
webapp/src/reducers/index.js
webapp/src/selectors/index.ts

PR link: https://github.com/mattermost/mattermost-plugin-jira/pull/887

[MI-2543] Review fixes on Jira PR #887 (Jira ticket link tooltip)

---

webapp/src/components/jira_ticket_tooltip/jira_ticket_tooltip.tsx

https://github.com/mattermost/mattermost-plugin-jira/pull/887

[MI-2612] Review fixes on Jira PR #887 (Add ticket link tooltip)

---

docs/administrator-guide/notification-management.md
webapp/src/components/modals/channel_subscriptions/channel_subscriptions_modal.scss
webapp/src/components/modals/channel_subscriptions/edit_channel_subscription.tsx
webapp/src/utils/styles.ts

PR: [#904](https://github.com/mattermost/mattermost-plugin-jira/pull/904)
[jiraFilterField.webm](https://user-images.githubusercontent.com/107465508/216004114-e3b79c39-bb51-4ded-b01b-5a083a5b79af.webm)

[MI-2698]: Review fixes done of PR #904

---

server/instances.go

https://github.com/mattermost/mattermost-plugin-jira/issues/902
https://github.com/mattermost/mattermost-plugin-jira/issues/902#issuecomment-1425275353

[MI-2738]:Added check to uninstall server if not found in KV store

---

server/instances.go

https://github.com/mattermost/mattermost-plugin-jira/pull/914

[MI-2781]:Fixed review comments for issue #902 and PR #914 on jira plugin

---

server/client.go
server/client_cloud.go
server/client_server.go
server/issue.go

https://github.com/mattermost/mattermost-plugin-jira/issues/912

[MI-2776]:Fixed issue #912 on jira plugin

---

docs/administrator-guide/notification-management.md

Jira PR: [#904](https://github.com/mattermost/mattermost-plugin-jira/pull/904)

[MI-2799]: Done review fixes of Jira PR #904

---

server/client.go
server/client_cloud.go
server/client_server.go
server/issue.go

https://github.com/mattermost/mattermost-plugin-jira/pull/915

[MI-2847]:Fixed the error while selecting projects above jira server 9.0.0

---

server/plugin.go

PR [#870](https://github.com/mattermost/mattermost-plugin-jira/pull/870)

[MI-2839]: Done the review fixes of a Jira PR #870

---

webapp/src/components/default_avatar/defaultAvatar.scss
webapp/src/components/jira_ticket_tooltip/index.ts
webapp/src/components/jira_ticket_tooltip/jira_ticket_tooltip.test.tsx
webapp/src/components/jira_ticket_tooltip/jira_ticket_tooltip.tsx
webapp/src/components/jira_ticket_tooltip/ticketStyle.scss
webapp/src/reducers/index.js
webapp/src/types/tooltip.ts
webapp/src/utils/jira_issue_metadata.test.tsx
webapp/src/utils/jira_issue_metadata.tsx

PR Link: https://github.com/mattermost/mattermost-plugin-jira/pull/887

[MI-2944] Review fixes on Jira PR #887 (Add link tooltip)

---

server/command.go
server/command_test.go
server/issue.go
server/user.go
server/user_test.go

Issue link: https://github.com/mattermost/mattermost-plugin-jira/issues/558

Fix issue #558: /jira assign should accept @username

---

webapp/src/components/default_avatar/defaultAvatar.scss
webapp/src/components/jira_ticket_tooltip/jira_ticket_tooltip.tsx
webapp/src/components/jira_ticket_tooltip/ticketStyle.scss

1. Replaced skeleton loader with spinner loader
[Demo video](https://user-images.githubusercontent.com/55234496/235860018-3cf7291f-cf92-455b-904a-9da062f1e987.webm)

[MI-3053] Review fixes on Jira PR #887 (Add link tooltip)

---

webapp/src/components/jira_ticket_tooltip/ticketStyle.scss

Link: https://github.com/mattermost/mattermost-plugin-jira/pull/887#issuecomment-1538292245

[MI-3064] Review fixes on jira PR #887(Add link tooltip)

---

webapp/src/components/jira_ticket_tooltip/jira_ticket_tooltip.tsx
webapp/src/components/jira_ticket_tooltip/ticketStyle.scss

Link: https://github.com/mattermost/mattermost-plugin-jira/pull/887#pullrequestreview-1421029464

[MI-3077] Review fixes on Jira PR #887 (Add link tooltip)

---

webapp/src/components/jira_ticket_tooltip/jira_ticket_tooltip.tsx

Link: https://github.com/mattermost/mattermost-plugin-jira/pull/887

[MI-3103] Review fixes on Jira PR #887 (Add link tooltip)

---

server/instance_cloud_oauth.go
server/issue.go
server/user_cloud_oauth.go
server/utils.go
server/webhook_jira.go
server/webhook_worker.go

For more context please refer:
https://community.mattermost.com/core/pl/c9in6u1np3ftjcz53ameogo5ka
Also added PKCE along with the authorization code for authorization:
https://github.com/mattermost/mattermost-plugin-jira/pull/949#discussion_r1221636177

[MI-3153] Fixed issue: comment webhook notification not working and added PKCE for authorization

---

assets/templates/oauth1/complete.html

Link: https://github.com/mattermost/mattermost-plugin-jira/pull/951#discussion_r1250908308
- Fixed lint issues and close the tab when user is successfully disconnected.

[MI-3266] Review fixes on Jira PR #951(Change user disconnect to HTTP POST)

---

server/issue.go
server/webhook.go
server/webhook_jira.go
server/webhook_worker.go

Link: https://github.com/mattermost/mattermost-plugin-jira/pull/953#issuecomment-1604073508

[MI-3282] Added logic to expand issue in comment webhook notification

---

server/utils.go
server/webhook_http_test.go

https://github.com/mattermost/mattermost-plugin-jira/issues/954

[MI-3338]:Fixed issue #954 'DM comment notifications not working'

---

server/webhook.go

Link: https://github.com/mattermost/mattermost-plugin-jira/pull/953#discussion_r1273592880
1. Added conditional for separation out the logic for Jira cloud and server

[MI-3335] Review fixes on Jira PR #953(Comment notification issue)

---

webapp/src/components/modals/channel_subscriptions/channel_subscriptions_modal.scss
webapp/src/components/modals/channel_subscriptions/select_channel_subscription.tsx

Fixed the alignment of `Create Subscriptions` button on 'Jira Subscriptions page`
https://github.com/mattermost/mattermost-plugin-jira/issues/957

[MI-3421]: Fixed the alignment of button on the Jira Subscriptions page

---

server/subscribe.go
webapp/src/components/modals/channel_subscriptions/__snapshots__/channel_subscription_filter.test.tsx.snap
webapp/src/components/modals/channel_subscriptions/channel_subscription_filter.tsx
webapp/src/types/model.ts

Developed a filter to receive subscription if you add the value or keep the value empty

[MI-3457]: Added a `Include or Empty` filter for subscription

---

server/webhook_parser.go

- Resolved the issue of Jira Bot DMs you when you mention yourself in a comment
https://github.com/mattermost/mattermost-plugin-jira/issues/857

[MI-3501]: Fixed Jira bot DMs you when you mention yourself in a comment

---

server/instance_cloud_oauth.go
server/instances.go

- Added logic to store the JWT instance data while installing the Oauth instance.
- Added logic to fetch the client for JWT instance in case the user is not connected to Oauth.

[MI-3620] Support Jira migration to Oauth:

---

server/client.go
server/client_cloud.go
server/client_server.go
server/http.go
server/issue.go
server/subscribe.go
webapp/src/actions/index.ts
webapp/src/components/data_selectors/jira_epic_selector/__snapshots__/jira_epic_selector.test.tsx.snap
webapp/src/components/modals/channel_subscriptions/__snapshots__/channel_subscription_filters.test.tsx.snap
webapp/src/components/modals/channel_subscriptions/__snapshots__/edit_channel_subscription.test.tsx.snap
webapp/src/components/modals/channel_subscriptions/channel_subscription_filter.test.tsx
webapp/src/components/modals/channel_subscriptions/channel_subscription_filters.test.tsx
webapp/src/components/modals/channel_subscriptions/edit_channel_subscription.test.tsx
webapp/src/components/modals/channel_subscriptions/edit_channel_subscription.tsx
webapp/src/components/modals/channel_subscriptions/index.ts
webapp/src/components/modals/channel_subscriptions/shared_props.ts
webapp/src/components/modals/create_issue/__snapshots__/create_issue_form.test.tsx.snap
webapp/src/testdata/cloud-get-create-issue-metadata-for-project-many-fields.json
webapp/src/testdata/cloud-get-create-issue-metadata-for-project.json
webapp/src/testdata/jira-issue-metadata-helpers.ts
webapp/src/testdata/server-get-create-issue-metadata-for-project-many-fields.json
webapp/src/types/model.ts
webapp/src/utils/jira_issue_metadata.test.tsx
webapp/src/utils/jira_issue_metadata.tsx

Fix review comment on PR: https://github.com/mattermost/mattermost-plugin-jira/pull/976

[MI-3628] Updated the code to return the status details in the meta data API
